import type { NextPage } from 'next'
import Welcome from '../components/Welcome'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className="h-screen bg-gray-300 flex flex-col items-center justify-center">
      <Head>
        <title> Home | Ojude | IleYoruba.org</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-center">
        <Welcome />
      </main>

      <footer className="">
        
      </footer>
    </div>
  )
}

export default Home
